CREATE TABLE vaersdata (
VAERS_ID real primary key,
RECVDATE date,
STATE char(2),
AGE_YRS real,
CAGE_YR real,
CAGE_MO real,
SEX char(1),
RPT_DATE date,
SYMPTOM_TEXT varchar(2048),
DIED char(1),
DATEDIED date,
L_THREAT char(1),
ER_VISIT char(1),
HOSPITAL char(1),
HOSPDAYS real,
X_STAY char(1),
DISABLE char(1),
RECOVD char(1),
VAX_DATE date,
ONSET_DATE date,
NUMDAYS real,
LAB_DATA varchar(750),
V_ADMINBY char(3),
V_FUNDBY char(3),
OTHER_MEDS varchar(750),
CUR_ILL varchar(500),
HISTORY varchar(750),
PRIOR_VAX varchar(256),
SPLTTYPE varchar(25));

CREATE TABLE vaersvax(
vaers_id real references vaersdata(vaers_id),
vax_type text,
vax_manu text,
vax_lot text,
vax_dose text,
vax_route text,
vax_site text,
vax_name text);

CREATE TABLE vaerssymptoms (
vaers_id real references vaersdata(vaers_id),
symptom1 text,
symptomversion1 real,
symptom2 text,
symptomversion2 real,
symptom3 text,
symptomversion3 real,
symptom4 text,
symptomversion4 real,
symptom5 text,
symptomversion5 real);